from . import cloud, operations, security

HANDLERS = {
    'dmarc': security.dmarc,
    'key-vault': security.key_vault_plan,
    'transcription': operations.transcription,
    'relocation': operations.relocation,
    'terraform': cloud.terraform_review,
    'graph-mail': cloud.graph_messages,
    'docker-selenium': operations.container_queue,
    'data-lifecycle': cloud.archive_candidates,
    'applocker-wdac': security.app_control,
    'azure-vpn': cloud.vpn_topology,
    'n8n-kubernetes': cloud.n8n_config,
    'sharepoint': cloud.sharepoint_owners,
    'purview-dlp': security.purview,
    'm365-hardening': security.hardening,
    'azure-arc': cloud.arc_inventory,
    'ai-lab': operations.ai_lab,
    'openpgp': security.pgp_context,
    'lexrag': cloud.document_retrieval,
    'glpi-defender': operations.glpi_inventory,
    'active-directory': security.ad_readiness,
    'monitoring': operations.monitoring,
    'patch-pilot': security.patch_pilot,
    'iis-cloudflare': security.iis_exposure,
    'kvm-recovery': operations.kvm_recovery,
    'wazuh-reporting': operations.weekly_report,
}
